In [2]:
import pandas as pd
import csv
import numpy as np

# from scipy.constants import carat

In [56]:
# 读取电压、容量曲线，注意要把标题去掉
curve_data = pd.read_csv('experiment-data/T2-pristine-0.1c-4-4.65.csv')
# curve_data.columns
# df_test = curve_data[curve_data['Cycle Index'] == 3]
# test_data = df_test[df_test['Step Type'] == "CC Chg"][["Voltage", "Spec. Cap."]]
# test_columns = ["Voltage_charge_1", "Capacity_charge_1",
#                    "Voltage_discharge_1", "Capacity_discharge_1"]
# test_data.rename(columns={'Voltage': test_columns[0], "Spec. Cap.": test_columns[1]}, inplace=True)
curve_data
# curve_data[["Voltage", "Spec. Cap."]]
# curve_data.iloc[:, 3:5]

      Cycle Index Step Type  Voltage  Spec. Cap.
0               1      Rest   3.7146        0.00
1               1      Rest   3.7148        0.00
2               1      Rest   3.7150        0.00
3               1      Rest   3.7152        0.00
4               1      Rest   3.7155        0.00
...           ...       ...      ...         ...
3046            1   CC DChg   3.0363      252.78
3047            1   CC DChg   3.0263      252.81
3048            1   CC DChg   3.0163      252.84
3049            1   CC DChg   3.0061      252.87
3050            1   CC DChg   3.0000      252.89

[3051 rows x 4 columns]

In [57]:
cycle_number = len(set(curve_data["Cycle Index"].values))
# 根据cycle_index判断有多少个循环，用于后续分布列
cycle_number

1

In [58]:
#
export_cycle = [1
    # , 6, 11, 16, 21, 26, 31, 36, 41
                ]
# 选取的循环，分别是0.5c 2c， 5c， 10c， 20c， 40c， 60c， 100c， 0.5c
cycle_data = pd.DataFrame(data=None)
for i in export_cycle: # 循环数设置,这一行是所有数据都选取

    new_columns = ["Voltage_charge_"+str(i), "Capacity_charge_"+str(i),
                   "Voltage_discharge_"+str(i), "Capacity_discharge_"+str(i)] # 每个循环的数据设计成
    df_cycle = curve_data[curve_data['Cycle Index'] == i]  # 选取第i圈循环的数据
    df_charge_i = df_cycle[df_cycle['Step Type'] == "CC Chg"][["Voltage", "Spec. Cap."]].reset_index(drop=True)
    df_charge_i.rename(columns={'Voltage': new_columns[0], "Spec. Cap.": new_columns[1]}, inplace=True)
    # print(df_charge_i)
    df_discharge_i = df_cycle[df_cycle['Step Type'] == "CC DChg"][["Voltage", "Spec. Cap."]].reset_index(drop=True)
    df_discharge_i.rename(columns={'Voltage': new_columns[2], "Spec. Cap.": new_columns[3]}, inplace=True)
    cycle_data = pd.concat([cycle_data, df_charge_i, df_discharge_i], axis=1)
cycle_data

,Voltage_charge_1,Capacity_charge_1,Voltage_discharge_1,Capacity_discharge_1
0,3.7279,0.00,4.6466,0.00
1,3.7389,0.00,4.6347,0.00
2,3.7520,0.00,4.6212,0.00
3,3.7646,0.01,4.6089,0.01
4,3.7750,0.01,4.5982,0.01
...,...,...,...,...
1568,NaN,NaN,3.0363,252.78
1569,NaN,NaN,3.0263,252.81
1570,NaN,NaN,3.0163,252.84
1571,NaN,NaN,3.0061,252.87
1572,NaN,NaN,3.0000,252.89

In [ ]:
# def cycle_data_process(data_path, ):

In [59]:
cycle_data.to_csv('T2-pristine-0.1c-4-4.65.csv', index=False)